import HistorySection from "@/components/sections/history";
import WelcomeSaldoSection from "@/components/sections/welcomeAndSaldo";
import { appConfig } from "@/constant/appConfig";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: `Transaction | ${appConfig.title}`,
  description: "Generated by create next app",
};
export default function Transaction() {
  return (
    <div className="flex gap-8 flex-col items-center justify-center">
      <WelcomeSaldoSection />
      <HistorySection />
    </div>
  );
}
