import { appConfig } from "@/constant/appConfig";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "../providers";
import NavbarComponent from "@/components/Atoms/navbar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: appConfig.title,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavbarComponent />
          <main className="container mx-auto px-20 pt-5">
            <Toaster position="bottom-left" reverseOrder={false} />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
