import WelcomeSaldoSection from "@/app/(main)/SectionWelcomeAndSaldo";
import React from "react";
import ServicesSection from "./section";
import { Metadata } from "next";
import { appConfig } from "@/constant/appConfig";
export const metadata: Metadata = {
  title: `Pembayaran | ${appConfig.title}`,
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div className="space-y-8">
      <WelcomeSaldoSection />
      <ServicesSection />
    </div>
  );
}
