import WelcomeSaldoSection from "@/app/(main)/SectionWelcomeAndSaldo";

import { appConfig } from "@/constant/appConfig";
import { Metadata } from "next";
import TopupSection from "./section";

export const metadata: Metadata = {
  title: `Top Up | ${appConfig.title}`,
  description: "Generated by create next app",
};
export default function TopupPage() {
  return (
    <div className="w-full flex flex-col gap-8">
      <WelcomeSaldoSection />
      <TopupSection />
    </div>
  );
}
