import TopupSection from "@/components/sections/topup";
import WelcomeSaldoSection from "@/components/sections/welcomeAndSaldo";
import { appConfig } from "@/constant/appConfig";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: `Top Up | ${appConfig.title}`,
  description: "Generated by create next app",
};
export default function TopupPage() {
  return (
    <div className="w-full flex flex-col gap-8">
      <WelcomeSaldoSection />
      <TopupSection />
    </div>
  );
}
