import { appConfig } from "@/constant/appConfig";
import "../../../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./../../../providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `Login - ${appConfig.title}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
